/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // VehicleIQ Dynamic Sleek Slate Palette (Supports Dark & Light Themes)
        'viq-surface-bright': 'var(--viq-surface-bright, #2A2A2A)',
        'viq-primary-fixed': '#FF9D66',
        'viq-secondary-fixed': '#FDBA74',
        'viq-on-primary-container': 'var(--viq-on-primary-container, #FFD1B8)',
        'viq-outline': 'var(--viq-outline, #4A4A4A)',
        'viq-on-tertiary-fixed': '#2B1500',
        'viq-inverse-primary': '#C86B3C',
        'viq-error-container': '#450A0A',
        'viq-surface-tint': '#C86B3C',
        'viq-surface-container': 'var(--viq-surface-container, #141414)',
        'viq-on-background': 'var(--viq-on-surface, #EDEDED)',
        'viq-tertiary-container': 'var(--viq-tertiary-container, #451A03)',
        'viq-tertiary-fixed': '#FDE68A',
        'viq-on-primary-fixed-variant': '#8C3D12',
        'viq-surface-container-highest': 'var(--viq-surface-container-highest, #222222)',
        'viq-on-error': '#FEF2F2',
        'viq-inverse-on-surface': '#1F1F1F',
        'viq-error': '#F87171',
        'viq-on-secondary': '#1C1917',
        'viq-on-error-container': '#FCA5A5',
        'viq-surface-variant': 'var(--viq-surface-container-high, #1E1E1E)',
        'viq-on-secondary-fixed-variant': '#7C2D12',
        'viq-primary': '#C86B3C',
        'viq-on-surface-variant': 'var(--viq-on-surface-variant, #A3A3A3)',
        'viq-on-primary': '#FFFFFF',
        'viq-background': 'var(--viq-background, #080808)',
        'viq-surface': 'var(--viq-surface, #0D0D0D)',
        'viq-surface-container-high': 'var(--viq-surface-container-high, #1A1A1A)',
        'viq-tertiary': '#F59E0B',
        'viq-outline-variant': 'var(--viq-outline-variant, #2E2E2E)',
        'viq-tertiary-fixed-dim': '#D97706',
        'viq-secondary-fixed-dim': '#FB923C',
        'viq-on-tertiary-container': '#FEF3C7',
        'viq-on-surface': 'var(--viq-on-surface, #F5F5F5)',
        'viq-on-tertiary-fixed-variant': '#78350F',
        'viq-surface-container-low': 'var(--viq-surface-container-low, #101010)',
        'viq-secondary-container': 'var(--viq-secondary-container, #3C1F15)',
        'viq-on-secondary-fixed': '#291107',
        'viq-inverse-surface': '#EDEDED',
        'viq-on-tertiary': '#1C1917',
        'viq-primary-fixed-dim': '#D97745',
        'viq-on-secondary-container': '#FFEDD5',
        'viq-on-primary-fixed': '#331405',
        'viq-surface-dim': 'var(--viq-background, #080808)',
        'viq-surface-container-lowest': 'var(--viq-surface-container-lowest, #050505)',
        'viq-primary-container': 'var(--viq-primary-container, #33170B)',
        'viq-secondary': '#D97745',
        brand: {
          50: '#fff7ed',
          100: '#ffedd5',
          500: '#f97316',
          600: '#ea580c',
          700: '#c2410c',
          800: '#9a3412',
          900: '#7c2d12',
        },
        slate: {
          800: '#1F1F1F',
          850: '#181818',
          900: '#121212',
          950: '#080808',
        }
      },
      fontFamily: {
        'jakarta': ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
        'sans': ['Plus Jakarta Sans', 'Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      spacing: {
        'space-lg': '1.5rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
        'space-xs': '0.25rem',
        'space-xl': '2.5rem',
        'gutter': '1.5rem',
        'gutter-sm': '0.75rem',
        'margin': '2.5rem',
        'margin-mobile': '1rem',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [],
}
